export const AUTHOR_NAMES: Record<string, string> = {
    kehlmann: 'Daniel Kehlmann',
    zeh: 'Juli Zeh',
    fitzek: 'Sebastian Fitzek',
    sueskind: 'Patrick Süskind',
    kracht: 'Christian Kracht',
    bachmann: 'Ingeborg Bachmann',
    kafka: 'Franz Kafka',
    borchert: 'Wolfgang Borchert',
    jaud: 'Tommy Jaud',
    regener: 'Sven Regener',
    strunk: 'Heinz Strunk',
    kling: 'Marc-Uwe Kling',
    stuckrad_barre: 'B. v. Stuckrad-Barre',
    evers: 'Horst Evers',
    loriot: 'Loriot',
    funke: 'Cornelia Funke',
    pantermueller: 'Alice Pantermüller',
    auer: 'Margit Auer',
    moers: 'Walter Moers',
    fabeln: 'Äsop & Grimm',
    fontane: 'Theodor Fontane',
    hoffmann: 'E.T.A. Hoffmann',
    rowling: 'Joanne K. Rowling'
};
